[package]
name = "rust_hello_world_window "
version = "0.1.0"
edition = "2021"

[lib]
test = false
path = "src/lib.rs"
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.63.0"

[dependencies]

