name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUST_HELLO_WORLD_VERSION: 1.0.0
  CARGO_TERM_COLOR: always

jobs:
  build-lin:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libclang-dev
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Compile RUST_HELLO_WORLD
        run: |
          cargo build --release
          cp target/release/librust_hello_world.so lin.xpl
          ldd lin.xpl
      - name: RUST_HELLO_WORLD Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rust_hello_world
          path: lin.xpl
          
  build-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Add Apple Silicon
        run: |
          rustup target add aarch64-apple-darwin
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Compile RUST_HELLO_WORLD
        run: |
          cargo build --release --target x86_64-apple-darwin
          cargo build --release --target aarch64-apple-darwin
          lipo -create target/x86_64-apple-darwin/release/librust_hello_world.dylib target/aarch64-apple-darwin/release/librust_hello_world.dylib -o mac.xpl
          otool -L mac.xpl
      - name: RUST_HELLO_WORLD Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rust_hello_world
          path: mac.xpl
          
  build-win:
    runs-on: windows-latest
    steps:
      - name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
        uses: KyleMayes/install-llvm-action@32c4866ebb71e0949e8833eb49beeebed48532bd
        if: matrix.config.os == 'windows-latest'
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
        if: matrix.config.os == 'windows-latest'
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Compile RUST_HELLO_WORLD
        run: |
          cargo build --release
          cp target/release/rust_hello_world.dll win.xpl
      - name: RUST_HELLO_WORLD Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rust_hello_world
          path: win.xpl                  
